# Generated by Django 4.1.3 on 2022-11-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoSheet',
            fields=[
                ('sheet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('kind', models.TextField()),
                ('compteur', models.IntegerField(default=0)),
                ('numsheet', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'PianoSheet',
                'managed': True,
            },
        ),
    ]
