# Generated by Django 4.1.3 on 2022-11-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0002_pianosheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='recipe_id',
            new_name='sheet_id',
        ),
    ]
