# Generated by Django 4.1.3 on 2022-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0003_rename_recipe_id_note_sheet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='recipe_nb',
        ),
        migrations.AddField(
            model_name='musician',
            name='sheet_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='e_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='email_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.TextField(blank=True),
        ),
    ]
